
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka-rogue
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-server:7.6.0
    init: confluentinc/confluent-init-container:2.8.0
  dataVolumeCapacity: 100Gi
  storageClass:
      name: gp2  
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka-rogue
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-server:7.6.0
    init: confluentinc/confluent-init-container:2.8.0
  dataVolumeCapacity: 100Gi
  storageClass:
    name: gp2
  dependencies:
    kRaftController:
      clusterRef:
        name: kraft-rogue            