name: Infrastructure Policy Enforcement

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    evaluate-policies:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install Conftest
              run: |
                LATEST_VERSION=$(wget -qO- "https://api.github.com/repos/open-policy-agent/conftest/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
                wget "https://github.com/open-policy-agent/conftest/releases/download/v${LATEST_VERSION}/conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz"
                tar xzf conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz
                sudo mv conftest /usr/local/bin




